version: "3"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  up:
    desc: up auth, redis, db, migrate and traefik and then backend
    cmds:
      - docker compose up -d

  down:
    desc: down all containers
    cmds:
      - docker compose down

  up:backend:
    desc: up backend container
    cmds:
      - docker compose -f docker-compose.backend.yaml up -d

  down:backend:
    desc: down backend container
    cmds:
      - docker compose -f docker-compose.backend.yaml down

  lint:
    desc: formatting project
    cmds:
      - go fmt ./...
      - golangci-lint run --fix