version: "3"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  build:
    desc: build backend side for develope
    cmds:
      - docker build -t self-dev-backend -f infra/Dockerfile .

  dev:
    desc: run backend in real time for develope
    cmds:
      - go run cmd/api/main.go

  lint:
    desc: formatting project
    cmds:
      - cd backend && go fmt ./...
      - cd backend && golangci-lint run --fix