version: "3"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  dev:up:
    desc: up (traefik, auth, redis, postgres)
    cmds:
      - docker compose -f infra/docker-compose.yaml up -d

  dev:down:
    desc: down (traefik, auth, redis, postgres)
    cmds: 
      - docker compose -f infra/docker-compose.yaml down

  dev:backend-up:
    desc: up backend
    cmds: 
      - docker compose -f infra/docker-compose.backend.yaml up --build -d

  dev:backend-down:
    desc: down backend
    cmds:
      - docker compose -f infra/docker-compose.backend.yaml down

  prod:up:
    desc: up in production (traefik, auth, redis, postgres)
    cmds:
      - docker compose -f infra/docker-compose.prod.yaml up -d

  prod:down:
    desc: down in production (traefik, auth, redis, postgres)
    cmds: 
      - docker compose -f infra/docker-compose.prod.yaml down

  prod:backend-up:
    desc: up backend in production
    cmds: 
      - docker compose -f infradocker-compose.prod.backend.yaml up -d

  prod:backend-down:
    desc: down backend in production
    cmds:
      - docker compose -f infra/docker-compose.prod.backend.yaml down

  lint:
    desc: formatting project
    cmds:
      - go fmt ./...
      - golangci-lint run --fix